cmdb/DjangoUeditor/urls.py
#coding:utf-8
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import patterns, url
else:
    from django.conf.urls.defaults import patterns, url

from views import get_ueditor_controller

urlpatterns = patterns('',
    url(r'^controller/$',get_ueditor_controller)
)

cmdb/api/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    FileName: urls.py
        Desc:
      Author: 苦咖啡
       Email: voilet@qq.com
    HomePage: http://blog.kukafei520.net
     Version: 0.0.1
  LastChange: 16/1/27 下午11:15
     History:   
"""

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       # 资产管理
                       url(r'^project/$', 'assets.api.api.type_list'),
                       url(r'^project/(?P<id>\d+)/$', 'assets.api.api.type_list_id'),
                       url(r'^user/.*$', 'assets.api.api.user_select'),

                       # 装机操作
                       url(r'^sn/.*$', 'assets.api.api.Sn_number'),
                       url(r'^cmdb/.*$', 'assets.api.api.CmdbUpdate'),

                       # nagios监控接口

                       url(r'^audit/list/.*$', 'audit.views.audit_list'),

                       url(r'^audit/$', 'audit.views.audit_save'),
                       # url(r'^create', 'assets.api.api.saltstack_create_config'),

                       # 安装完成上报接口
                       url(r'^system_install/$', 'assets.value_class.index.install_ok'),
                       url(r'^alert/$', 'malfunction.views.FaultApi'),
                       url(r'^monitor/http', 'monitor.views.HttpMonitorApi'),
                       url(r'^monitor/log', 'api.monitor_api.HttpMonitorLog'),
                       url(r'^xls/', 'api.cmdb_excel.xls_select'),
                       url(r'^cdn/', 'api.cmdb_excel.xls_cdn'),

                       )

cmdb/assets/api/urls.py
#!/usr/bin/env python
#-*- coding: utf-8 -*-
#=============================================================================
#     FileName:
#         Desc:
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      Version: 0.0.1
#   LastChange: 
#      History:
#=============================================================================

from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    #资产管理
    url(r'^project/$', 'assets.api.api.type_list'),
    url(r'^project/(?P<id>\d+)/$', 'assets.api.api.type_list_id'),
    url(r'^user/.*$', 'assets.api.api.user_select'),

    #装机操作
    url(r'^sn/.*$', 'assets.api.api.Sn_number'),
    url(r'^cmdb/.*$', 'assets.api.api.CmdbUpdate'),

    #nagios监控接口

    url(r'^audit/list/.*$', 'audit.views.audit_list'),

    url(r'^audit/$', 'audit.views.audit_save'),
    # url(r'^create', 'assets.api.api.saltstack_create_config'),

    #安装完成上报接口
    url(r'^system_install/$', 'assets.value_class.index.install_ok'),
    url(r'^alert/$', 'malfunction.views.FaultApi'),

)

cmdb/mysite/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
#     FileName:
#         Desc:
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      Version: 0.0.1
#   LastChange: 2013-02-20 14:52:11
#      History:
# =============================================================================

from django.conf.urls import patterns, include, url
from mysite.settings import MEDIA_ROOT
from django.contrib import admin
from settings import BASE_DIR

admin.autodiscover()

urlpatterns = patterns('',
                       (r'^upload/(?P<path>.*)$', 'django.views.static.serve', {'document_root': "%s/upload" % BASE_DIR}),

                       url(r'accounts/', include("accounts.urls")),
                       # url(r'^$', 'salt_ui.auto.auto_index_class.auto_index'),
                       url(r'^$', 'salt_ui.views.index.salt_index_new'),
                       url(r'^login/$', 'salt_ui.views.index.auth_login'),
                       url(r'^test/$', 'salt_ui.views.index.test'),
                       # 日志
                       url(r'^logs/salt/', 'salt_ui.views.api_log_class.salt_data_log'),
                       url(r'^logs/host/', "audit.views.audit_list"),

                       # 搜索
                       # url(r'^search/$', 'assets.views.search'),
                       # salt_ui
                       url(r'salt/', include("salt_ui.urls")),
                       # 资产管理
                       url(r'assets/', include("assets.urls")),
                       # url(r'',include(salt_ui.urls)),
                       # 运维自动化
                       url(r'auto/', include("salt_ui.auto.urls")),
                       # 资产api
                       url(r'api/', include("api.urls")),
                       url(r'conf/', include("config.urls")),

                       # 审计模块
                       url(r'^audit/', include("audit.urls")),

                       # admin
                       url(r'^admin/', include(admin.site.urls)),

                       # swan发布接口
                       url(r'swan/', include("swan.urls")),

                       # 故障管理
                       url(r'^incident/', include("malfunction.urls")),

                       # 监控
                       url(r'^monitor/', include("monitor.urls")),

                       # message
                       url(r'^message/', include("message.urls")),

                       # 权限组
                       url(r'^auth/', include("cmdb_auth.urls")),

                       url(r'^ops/doc/$', 'salt_ui.views.index.OpsDoc'),
                       url(r'^api/project/$', 'assets.api.api.type_list'),
                       url(r'^api/project/(?P<id>\d+)/$', 'assets.api.api.type_list_id'),

                       url(r'^ueditor/', include('DjangoUeditor.urls')),


                       # url(r'^summernote/', include('django_summernote.urls')),
                       #
                       )

cmdb/swan/models.py
# coding:utf-8

import datetime
from django.db import models
from users.models import CustomUser
from assets.models import Project
from uuidfield import UUIDField


class Apply(models.Model):
    uuid = UUIDField(auto=True, primary_key=True)
    applyer = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"申请人")
    project_name = models.CharField(max_length=20, blank=True, null=True, verbose_name=u"项目名")
    module_name = models.CharField(max_length=200, blank=True, null=True, verbose_name=u"模块名")
    module_type = models.PositiveIntegerField(blank=True, null=True, verbose_name=u"是否有参数")
    module_tgt = models.CharField(max_length=50, blank=True, null=True, verbose_name=u"参数值")
    qa = models.CharField(max_length=20, blank=True, null=True, verbose_name=u"测试人员")
    op = models.CharField(max_length=20, blank=True, null=True, verbose_name=u"运维人员")
    comment = models.TextField(blank=True, null=True, verbose_name=u"备注")
    status = models.PositiveIntegerField(blank=True, null=True, verbose_name=u'状态')
    u"""
    status
    0   申请状态
    1   测试完成
    2   发布完成
    """
    date_added = models.DateTimeField(auto_now=True, default=datetime.datetime.now(), null=True, verbose_name=u"仓建时间")
    date_one = models.DateTimeField(null=True, verbose_name=u"测试完成时间")
    date_ended = models.DateTimeField(null=True, verbose_name=u"发布时间")

    def __unicode__(self):
        return self.applyer


class SwanLog(models.Model):
    uuid = UUIDField(auto=True, primary_key=True)
    username = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"发布人")
    userID = models.CharField(max_length=128, blank=True, null=True, verbose_name=u"发布人id")
    project_name = models.CharField(max_length=20, blank=True, null=True, verbose_name=u"项目名")
    project_uuid = models.CharField(max_length=64, blank=True, null=True, verbose_name=u"项目id")
    swan_name = models.CharField(max_length=64, blank=True, null=True, verbose_name=u"swan name")
    module_name = models.CharField(max_length=200, blank=True, null=True, verbose_name=u"模块名")
    module_args = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"是否有参数")
    status = models.BooleanField(verbose_name=u'发布状态', default=0)
    message = models.TextField(verbose_name=u'日志', blank=True, null=True)
    update_log = models.TextField(verbose_name=u'更新记录', blank=True, null=True)
    swan_datetime = models.DateTimeField(auto_now=True, default=datetime.datetime.now(), null=True,
                                         verbose_name=u"发布时时")

    def __unicode__(self):
        return self.project_name

    class Meta:
        managed = True
        verbose_name = u"发布日志"

cmdb/audit/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
#     FileName:
#         Desc:
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      Version: 0.0.1
#      History:
# =============================================================================

import json, time, urllib
from django.shortcuts import render_to_response, get_object_or_404
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from audit.models import ssh_audit
from django.views.decorators.csrf import csrf_exempt
# 登录
from cmdb_auth.no_auth import check_auth

import requests, re


@csrf_exempt
def audit_save(request):
    """
    用户操作记录入库
    user_name = models.CharField(max_length=20, verbose_name=u'操作用户')
    bash_shell = models.TextField(verbose_name=u'命令')
    audit_data_time = models.DateTimeField(verbose_name=u'操作时间')
    server_ip = models.IPAddressField(verbose_name=u'服务器ip')
    """
    if request.method == 'POST':
        user_name = request.POST.get("user_name")
        bash_shell = request.POST.get("bash_shell")
        audit_data_time = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time()))
        server_ip = request.POST.get("server_ip")
        # data = ssh_audit_log(user_name, bash_shell, audit_data_time, server_ip)
        ssh_audit_data = ssh_audit(user_name=user_name, bash_shell=bash_shell, audit_data_time=audit_data_time,
                                   server_ip=server_ip)
        s = ssh_audit_data.save()
        if s:
            return HttpResponse(json.dumps({"status": 200, "result": u"已入库"}, ensure_ascii=False, indent=4, ))
    return HttpResponse(json.dumps({"status": 403, "result": u"error"}, ensure_ascii=False, indent=4, ))


@csrf_exempt
def audit_list(request):
    """
    用户审计记录
    :param requests:
    :return:
    """
    status = check_auth(request, "server_audit")
    if not status:
        return render_to_response('default/error_auth.html', locals(), context_instance=RequestContext(request))

    audit_data = ssh_audit.objects.all().order_by("-audit_data_time")
    return render_to_response('audit/list.html', locals(), context_instance=RequestContext(request))


@csrf_exempt
def audit_select(request):
    """
    查询服务器操作记录
    """
    # ip = "192.168.8.225"
    if request.method == 'POST':
        ip = request.POST.get("ip")
        try:
            audit_page = int(request.POST.get("num"))
        except:
            audit_page = 0
        if audit_page > 0:
            num = audit_page
            audit_data = ssh_audit.objects.filter(server_ip=ip).order_by("-audit_data_time")[:num]
        else:
            audit_data = ssh_audit.objects.filter(server_ip=ip).order_by("-audit_data_time")

        data = []
        for i in audit_data:
            # content[ip]
            data.append({"bash_shell": "%s  %s     %s" % (i.user_name, i.audit_data_time, i.bash_shell)})
        # print data

        return HttpResponse(json.dumps({"status": 200, "result": data}, ensure_ascii=False, indent=4), content_type="application/json")

    return HttpResponse(json.dumps({"status": 403, "result": "error"}, ensure_ascii=False, indent=4), content_type="application/json")

cmdb/templates/server_idc/add_batch.html
{% extends 'assets/base.html' %}
{% block content %}
<script type="text/javascript" src="/static/js/from_js/jquery.validVal.js"></script>
<link rel="stylesheet" href="/static/css/from_cs/jquery.validator.css">
<script type="text/javascript" src="/static/js/from_js/zh_CN.js"></script>
<style>
   .col-sm-11 .n-invalid{
    border: 1px solid #ff0000;
}
</style>
{% if batch %}
    <div id="content-block" class="col-sm-12">
        <pre>批量添加主机</pre>
        <form class="form-horizontal" action=""   method="post" name="horizontal" role="form" autocomplete="off" data-validator-option="{theme:'yellow_right_effect'}">{% csrf_token %}
        <textarea class="form-control" rows="10" data-rule="required" placeholder="l-zhany6.ops.prod.cn1.jumei.com	192.168.1.1 default DELL CentOS x86_64" name="add_batch"></textarea>
    <div class="clearfix"></div><br>
        <button type="submit" class="btn btn-success btn-block">保存</button>
        </form>

    </div>
    {% else %}
    <div id="content-block" class="col-sm-12">
            <pre>批量添加失败主机列表</pre>
             <pre>{% for i in error %}{{ i }}
{% endfor %}{% endif %}</pre>


{% endblock content %}

cmdb/templates/server_idc/add_return.html
{% if add_return %}
<div class="alert alert-success alert-dismissable">
	 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	<h4>
		{{ hostname }} 添加成功!
	</h4>

</div>
{% else %}
<div class="alert alert-success alert-danger">
	 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	<h4>
		{{ hostname }} 添加失败!
	</h4>

</div>
{% endif %}

cmdb/templates/server_idc/ajax_item.html
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
<script type="text/javascript" charset="utf-8" src="/static/js/bootstrap.min.js"></script>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>
				主机名
			</th>
			<th>
				机房
			</th>
			<th>
				eth1
			</th>
			<th>
				内存
			</th>
            <th>
				核数
			</th>
            <th>
				硬盘
			</th>
            <th>
				型号
			</th>
			<th>
				系统
			</th>
			<th>
				业务
			</th>

		</tr>
	</thead>
	<tbody>
		<tr >
			<td width="200">
				{{ node.node_name }}
			</td>
			<td width="125">
				{{ node.idc }}
			</td>
			<td width="150">
				{{ node.eth1 }}
			</td>
			<td width="80">
				{% widthratio node.memory 1024 1 %}G
			</td>
            <td width="100">
				{% if node.core_num %}{{ node.core_num }}{% endif %}
			</td>
            <td width="100">
                {% if node.hard_disk %}
				{{ node.hard_disk }} G
                    {% else %}
                    无数据
                {% endif %}
			</td>
            <td width="100">
				{{ node.brand }}
			</td>
			<td width="160">
				{{ node.system }} - {{ node.system_cpuarch }}
			</td>
			<td width="100">
                   {% if node.business.id  %}<a href="{% url 'business_item_ajax' %}?id={{ node.business.id }}" class="fancybox fancybox.ajax">{{ node.business }}</a>{% endif %}
			</td>
		</tr>
	</tbody>
    </table>
<pre style="height: 400px;">
远控卡: {% if node.internal_ip %}{{ node.internal_ip }}{% else %}<span style="color:#ff110a">未填写</span>{% endif %}
MAC: {% if node.mac %}{{ node.mac }}{% else %}<span style="color:#ff110a">未填写</span>{% endif %}
eth2: {% if node.eth2 %}{{ node.eth2 }}{% else %}<span style="color:#ff110a">未填写</span>{% endif %}
环境: {% if node.env %}{{ node.env }}{% else %}<span style="color:#ff110a">未填写</span>{% endif %}
机房: {% if node.idc %}{{ node.idc }}{% else %}<span style="color:#ff110a">未填写</span>{% endif %}
机柜: {% if node.cabinet %}{% if node.room_number %}{{ node.room_number }} - {% endif %}{{ node.cabinet }} - {{ node.server_cabinet_id }}{% else %}<span style="color:#ff110a">未填写</span>{% endif %}
资产编号: {% if node.number %}{{ node.number }}{% else %}<span style="color:#ff110a">未填写</span>{% endif %}
SN编号: {% if node.server_sn %}{{ node.server_sn }}{% else %}<span style="color:#ff110a">未填写</span>{% endif %}
保修期: {% if node.guarantee_date %}{{ node.guarantee_date }}{% else %}<span style="color:#ff110a">未填写</span>{% endif %}
快速服务编码: {% if node.Services_Code %}{{ node.Services_Code }}{% else %}<span style="color:#ff110a">未填写</span>{% endif %}
创建日期: {{ node.create_time}}
交换机接口: {{ node.switch_port }}

上次修改人:{% if node.old_editname %}<button  class="btn btn-xs btn-primary" data-toggle="modal">{{ node.old_editname }}</button>{% endif %}
上次修时间:{% if node.old_editdatetime %}<button  class="btn btn-xs btn-primary" data-toggle="modal">{{ node.old_editdatetime }}</button>{% endif %}
本次修改人:{% if node.edit_username %}<button  class="btn btn-xs btn-success" data-toggle="modal">{{ node.edit_username }}</button>{% endif %}
本次修时间:{% if node.edit_datetime  %}<button  class="btn btn-xs btn-success" data-toggle="modal">{{ node.edit_datetime }}</button>{% endif %}




</pre>
<h3>备注:</h3>
<p>{% if node.editor %}{{ node.editor }}{% endif %}</p>

cmdb/templates/server_idc/api.html
<pre>
{% for i in server_list %}{{ i.eth1 }}          {{ i.business }}
{% endfor %}
</pre>

cmdb/templates/server_idc/auth_type.html
{% block content %}
        <div class="form-group">
            <label class="control-label col-sm-2 col-lg-2 " for="id_user_name">选择需要授权主机</label>
            <div class=" col-sm-5 col-lg-5 ">
                <table class="table table-condensed table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>
                                <input type="checkbox" value="" id="select_all" /> 全选
                            </th>
                        </tr>
                    </thead>
                    <tbody id="tab-add">
                        {% for i in server_list %}
                            <tr>
                            {% if i.status == 1 %}
                                {% if i.uuid not in ip_list %}
                                    <td> <input type="checkbox" value="{{ i.uuid }}" name="node" /> {{ i.eth1 }}</td>
                                {% endif %}
                            {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class=" col-sm-5 col-lg-5 ">
                <table class="table table-condensed table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>
                                已分配权限主机
                            </th>
                            <th>权限</th>
                            <th>
                                删除
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in data %}
                            {% if i.node.status == 1 %}
                                <tr id="{{ i.id }}">
                                        <td>{{ i.node.eth1 }}</td>
                                        <td> <a class="btn btn-xs btn-success" href="{{ i.id }}">{% if i.auth %}管理员{% else %}普通用户{% endif %}</a></td>
                                        <td> <a class="save_delete" id="{{ i.id }}" value="{{ i.node.uuid }}" name="{{ i.node.eth1 }}" href="/accounts/server/auth/delete/?uuid={{ i.node.uuid }}&auth_id={{ user_data.uuid }}" onclick="return false">删除</a></td>
                                </tr>
                            {% endif %}
                        {% endfor %}

                    </tbody>
                </table>
            </div>

        </div>

<script>
    $('.save_delete').unbind('click').bind('click',function(){
      $("tr[id='"+$(this).attr("id")+"']").remove();
      var node_name_data= $(this).attr("name");
      var node_name_uuid= $(this).attr("value");
      $.ajax({
         type: "GET",
         node_name_data: $(this).attr("name"),
         url: $(this).attr("href") }).done(function( data ) {
          $("#tab-add").append("<tr>"
                               +"<td>"+"<input type=\"checkbox\" value=" + node_name_uuid + " name=\"node_name\">" + node_name_data + "</td>"
                           +"</tr>");
         return false;
      });
    });
    // 请求保存
     $('.edit-save').unbind('click').bind('click',function(){
          $.ajax({
              type: "POST",
              url: $(this).attr("href"),                  // 提交的页面
              data: $('#form_data').serialize(), // 从表单中获取数据
              dataType:'text',
              success: function(msg){
                  // alert(msg);
                  $("#edit_result").html(msg);
              }
          });return false;
         });
    $(document).on("click","#select_all",function(e){
           var selected = $("#select_all").prop("checked");
           if(selected){
             $("input[name='node']").prop('checked',true);
           }else{
             $("input[name='node']").prop("checked",false);
           }
         });
</script>

{% endblock content %}

cmdb/templates/server_idc/base.html
{% extends 'default/base.html' %}
{% block left %}
    <div class="panel-group" id="panel-349889"><!--  panel panel-primary -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><a class="panel-title" data-toggle="collapse" data-parent="#panel-349889" href="#panel-element-290449">资产管理</a></h3>
            </div>
            <div id="panel-element-290449" class="panel-collapse collapse in">
                <div class="panel-body">
                    <p><a href="/assets/server/add/" >添加真实机</a></p>
                    <p><a href="/assets/server/vm/" >申请虚拟机</a></p>
                    <p><a href="/assets/server/batch/" >批量添加资产</a></p>
                    <p><a href="/assets/server/" >服务器列表</a></p>
                    {% if "admin" in  request.user.department  %}
                        <p><a href="/assets/server/approve/" >待审核虚拟机</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><a class="panel-title" data-toggle="collapse" data-parent="#panel-349889" href="#panel-element-85212785">机房管理</a></h3>
            </div>
            {% if "/assets/server/room/" in  request.path  %}
                <div id="panel-element-85212785" class="panel-collapse collapse in">
            {% elif "/assets/server/room_list/" in  request.path %}
                    <div id="panel-element-85212785" class="panel-collapse collapse in">
            {% else %}
                        <div id="panel-element-85212785" class="panel-collapse collapse">
            {% endif %}
            <div class="panel-body">
                <p><a href="/assets/server/room/add/" >添加机房</a></p>
                <p><a href="/assets/server/room/list/" >机房列表</a></p>
            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a class="panel-title" data-toggle="collapse" data-parent="#panel-349889" href="#panel-element-52457896">项目分类</a></h3>
                        </div>
                        {% if "/assets/server/server_type/" in  request.path  %}
                            <div id="panel-element-52457896" class="panel-collapse collapse in">
                        {% else %}
                                <div id="panel-element-52457896" class="panel-collapse collapse">
                        {% endif %}
                        <div class="panel-body">
                            {% for i in server_type %}
                                <p><a href="/assets/server/server_type/{{ i.id }}/" >{{ i }}</a></p>
                            {% endfor %}
                        </div>
                                </div>
                            </div>


                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title">
                                        <a class="panel-title" data-toggle="collapse" data-parent="#panel-349889" href="#panel-element-564813221">项目管理</a></h3>
                                </div>
                                <div id="panel-element-564813221" class="panel-collapse collapse in">
                                    <div class="panel-body">
                                        <p><a href="/assets/server/type/list/" >项目列表</a></p>
{#                                        {{  request.user.department }}#}
                                        {% if  request.user.department_id == 1 or request.user.is_superuser == 1 %}
                                            <p><a href="/assets/server/type/add/" >添加项目</a></p>
                                            <p><a href="/assets/product/add/" >添加产品线</a></p>
                                            <p><a href="/assets/product/list/" >产品线列表</a></p>
                                        {% endif %}
                                    </div>
                                    <div class="panel-body">
                                        <p><a href="/assets/server/host_without_business/" > 未分配项目主机</a></p>
                                        <p><a href="/assets/server/edit/log/" > 操作日志</a></p>
                                    </div>
                                </div>
                            </div>

                    </div>
{% endblock %}

{% block content %}
{% endblock content %}

cmdb/templates/server_idc/business_item_widget.html
{#<h1>{{ item }}</h1>#}
<p>主要联系人: {{ item.project_contact }} 第二联系人: {{ item.project_contact_backup }}</p>
<ul class="nav nav-pills">
    <li ><button href="{% url 'business_host_list' item.id %}" class="btn btn-primary btn-action click" >项目环境</button></li>
    <li>  <button href="{% url 'business_user_edit' item.id %}" class="btn btn-primary btn-action click" >权限管理</button> </li>
    <li ><button href="{% url 'project_doc' item.id %}" class="btn btn-primary btn-action click">维护文档</button></li>
    <li ><button href="{% url 'project_edit_ajax' item.id %}" class="btn btn-primary btn-action click">项目修改</button></li>
</ul>
<p></p>
<div id="status">

</div>

<script>
 $(function(){
    $('.click').unbind('click').bind('click',function(){
      var url= $(this).attr("href");
         $.ajax({
             type: "GET",
             url: url }).done(function( data ) {
             $("#status").html(data);
         });
         $(".nav-pills >li > button").attr("class", "btn btn-primary btn-action click");
         $(this).attr("class", "btn btn-success btn-action click");
    });

     $('.click-save').unbind('click').bind('click',function(){
         var url= $(this).attr("href");
         $.ajax({
             type: "POST",
             url: $(this).attr("href"),                  // 提交的页面
             data: $('#form_data').serialize(), // 从表单中获取数据
             dataType:'text',
             success: function(msg){
                 $("#data_ok").html(msg)                    // 设置表单提交完成使用方法
             }
         });
      });

 })

</script>

cmdb/templates/server_idc/download.html
<div class="col-md-12 column">
    <div class="alert alert-success alert-dismissable">
         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4>
            提醒!
            {% if data == "pdf" %}
            </h4> <strong>Warning!</strong> pdf文件已生成请点击 <a href="/static/pdf/fun.pdf" target="_blank" class="alert-link">下载</a>
            {% else %}
            </h4> <strong>Warning!</strong> excel文件已生成请点击 <a href="/static/pdf/fun.xls" target="_blank" class="alert-link">下载</a>
            {% endif %}
    </div>
</div>

cmdb/templates/server_idc/server_type_del.html
{% include 'default/header.html' %}
{% include 'default/assets_left.html' %}
{% load pagination_tags %}
{% autopaginate list_server_type 20 %}
<div id="content-block" class="col-sm-11 col-md-10">
    <pre>业务列表</pre>
    <div id="salt_type_list">
    <pre>{% for i in list_server_type %}{{ i.server_type }}
{% endfor %}
    </pre>
        <div  class="voilet_page">
             {% paginate %}
        </div>
    </div>
</div>
{% include 'default/footer.html' %}
{% include 'default/jquery.html' %}

cmdb/templates/server_idc/zabbix.html
{% extends 'assets/base.html' %}
{% block content %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Zabbix信息列表 | List Zabbix.</h2>
    </div>
    <div class="col-lg-2">
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5> Zabbix信息列表 </h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user"></ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="ibox-content">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">名称</th>
                            <th class="text-center">类别</th>
                            <th class="text-center">状态</th>
                            <th class="text-center">时间</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in records %}
                            <tr>
                                <td class="text-center">{{ i.name }}</td>
                                <td class="text-center">{{ i.type }}</td>
                                {% ifequal i.status 1 %}
                                    <td class="text-center text-info">{{ i.get_status_display }}</td>
                                {% else %}
                                    <td class="text-center text-danger">{{ i.get_status_display }}</td>
                                {% endifequal %}

                                <td class="text-center">{{ i.time|date:"Y-m-d H:i:s" }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}