cmdb/DjangoUeditor/urls.py
#coding:utf-8
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import patterns, url
else:
    from django.conf.urls.defaults import patterns, url

from views import get_ueditor_controller

urlpatterns = patterns('',
    url(r'^controller/$',get_ueditor_controller)
)

cmdb/api/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    FileName: urls.py
        Desc:
      Author: 苦咖啡
       Email: voilet@qq.com
    HomePage: http://blog.kukafei520.net
     Version: 0.0.1
  LastChange: 16/1/27 下午11:15
     History:   
"""

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       # 资产管理
                       url(r'^project/$', 'assets.api.api.type_list'),
                       url(r'^project/(?P<id>\d+)/$', 'assets.api.api.type_list_id'),
                       url(r'^user/.*$', 'assets.api.api.user_select'),

                       # 装机操作
                       url(r'^sn/.*$', 'assets.api.api.Sn_number'),
                       url(r'^cmdb/.*$', 'assets.api.api.CmdbUpdate'),

                       # nagios监控接口

                       url(r'^audit/list/.*$', 'audit.views.audit_list'),

                       url(r'^audit/$', 'audit.views.audit_save'),
                       # url(r'^create', 'assets.api.api.saltstack_create_config'),

                       # 安装完成上报接口
                       url(r'^system_install/$', 'assets.value_class.index.install_ok'),
                       url(r'^alert/$', 'malfunction.views.FaultApi'),
                       url(r'^monitor/http', 'monitor.views.HttpMonitorApi'),
                       url(r'^monitor/log', 'api.monitor_api.HttpMonitorLog'),
                       url(r'^xls/', 'api.cmdb_excel.xls_select'),
                       url(r'^cdn/', 'api.cmdb_excel.xls_cdn'),

                       )

cmdb/mysite/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
#     FileName:
#         Desc:
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      Version: 0.0.1
#   LastChange: 2013-02-20 14:52:11
#      History:
# =============================================================================

from django.conf.urls import patterns, include, url
from mysite.settings import MEDIA_ROOT
from django.contrib import admin
from settings import BASE_DIR

admin.autodiscover()

urlpatterns = patterns('',
                       (r'^upload/(?P<path>.*)$', 'django.views.static.serve', {'document_root': "%s/upload" % BASE_DIR}),

                       url(r'accounts/', include("accounts.urls")),
                       # url(r'^$', 'salt_ui.auto.auto_index_class.auto_index'),
                       url(r'^$', 'salt_ui.views.index.salt_index_new'),
                       url(r'^login/$', 'salt_ui.views.index.auth_login'),
                       url(r'^test/$', 'salt_ui.views.index.test'),
                       # 日志
                       url(r'^logs/salt/', 'salt_ui.views.api_log_class.salt_data_log'),
                       url(r'^logs/host/', "audit.views.audit_list"),

                       # 搜索
                       # url(r'^search/$', 'assets.views.search'),
                       # salt_ui
                       url(r'salt/', include("salt_ui.urls")),
                       # 资产管理
                       url(r'assets/', include("assets.urls")),
                       # url(r'',include(salt_ui.urls)),
                       # 运维自动化
                       url(r'auto/', include("salt_ui.auto.urls")),
                       # 资产api
                       url(r'api/', include("api.urls")),
                       url(r'conf/', include("config.urls")),

                       # 审计模块
                       url(r'^audit/', include("audit.urls")),

                       # admin
                       url(r'^admin/', include(admin.site.urls)),

                       # swan发布接口
                       url(r'swan/', include("swan.urls")),

                       # 故障管理
                       url(r'^incident/', include("malfunction.urls")),

                       # 监控
                       url(r'^monitor/', include("monitor.urls")),

                       # message
                       url(r'^message/', include("message.urls")),

                       # 权限组
                       url(r'^auth/', include("cmdb_auth.urls")),

                       url(r'^ops/doc/$', 'salt_ui.views.index.OpsDoc'),
                       url(r'^api/project/$', 'assets.api.api.type_list'),
                       url(r'^api/project/(?P<id>\d+)/$', 'assets.api.api.type_list_id'),

                       url(r'^ueditor/', include('DjangoUeditor.urls')),


                       # url(r'^summernote/', include('django_summernote.urls')),
                       #
                       )

cmdb/swan/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
#     FileName: urls.py
#         Desc: 2015-15/1/5:下午1:20
#       Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      History: 
# =============================================================================

from django.conf.urls import patterns, url




urlpatterns = patterns('',
    # 项目配置自动化发布
    url(r'push/$', "swan.views.swan_push"),
    url(r'release/$', "swan.views.swan_release"),
    url(r'log/(?P<uuid>[^/]+)/$$', "swan.views.SwanSelectLog", name="SwanSelectLog"),
    url(r'swan_select/$', "swan.views.swan_select"),
    url(r'^swan_select_myfrom/$', "swan.views.swan_select_myfrom"),
    url(r'^swan_select_botton/$', "swan.views.swan_select_button"),
    url(r'swan_select_tgt/$', "swan.views.swan_select_tgt"),
    url(r'^websocket/$', "swan.views.swan_websocket"),
    url(r'^apply/(?P<uuid>[^/]+)/$', "swan.views.swan_apply"),
    url(r'^apply/p/$', "swan.views.apply_project"),
    url(r'^apply/exec/$', "swan.views.apply_auto"),
    url(r'$', "swan.views.swan_index"),
)

cmdb/swan/models.py
# coding:utf-8

import datetime
from django.db import models
from users.models import CustomUser
from assets.models import Project
from uuidfield import UUIDField


class Apply(models.Model):
    uuid = UUIDField(auto=True, primary_key=True)
    applyer = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"申请人")
    project_name = models.CharField(max_length=20, blank=True, null=True, verbose_name=u"项目名")
    module_name = models.CharField(max_length=200, blank=True, null=True, verbose_name=u"模块名")
    module_type = models.PositiveIntegerField(blank=True, null=True, verbose_name=u"是否有参数")
    module_tgt = models.CharField(max_length=50, blank=True, null=True, verbose_name=u"参数值")
    qa = models.CharField(max_length=20, blank=True, null=True, verbose_name=u"测试人员")
    op = models.CharField(max_length=20, blank=True, null=True, verbose_name=u"运维人员")
    comment = models.TextField(blank=True, null=True, verbose_name=u"备注")
    status = models.PositiveIntegerField(blank=True, null=True, verbose_name=u'状态')
    u"""
    status
    0   申请状态
    1   测试完成
    2   发布完成
    """
    date_added = models.DateTimeField(auto_now=True, default=datetime.datetime.now(), null=True, verbose_name=u"仓建时间")
    date_one = models.DateTimeField(null=True, verbose_name=u"测试完成时间")
    date_ended = models.DateTimeField(null=True, verbose_name=u"发布时间")

    def __unicode__(self):
        return self.applyer


class SwanLog(models.Model):
    uuid = UUIDField(auto=True, primary_key=True)
    username = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"发布人")
    userID = models.CharField(max_length=128, blank=True, null=True, verbose_name=u"发布人id")
    project_name = models.CharField(max_length=20, blank=True, null=True, verbose_name=u"项目名")
    project_uuid = models.CharField(max_length=64, blank=True, null=True, verbose_name=u"项目id")
    swan_name = models.CharField(max_length=64, blank=True, null=True, verbose_name=u"swan name")
    module_name = models.CharField(max_length=200, blank=True, null=True, verbose_name=u"模块名")
    module_args = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"是否有参数")
    status = models.BooleanField(verbose_name=u'发布状态', default=0)
    message = models.TextField(verbose_name=u'日志', blank=True, null=True)
    update_log = models.TextField(verbose_name=u'更新记录', blank=True, null=True)
    swan_datetime = models.DateTimeField(auto_now=True, default=datetime.datetime.now(), null=True,
                                         verbose_name=u"发布时时")

    def __unicode__(self):
        return self.project_name

    class Meta:
        managed = True
        verbose_name = u"发布日志"

cmdb/config/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
# FileName: forms.py
# Desc: 2015-15/11/16:下午4:14
# Author: 苦咖啡
#        Email: voilet@qq.com
#     HomePage: http://blog.kukafei520.net
#      History: 
# =============================================================================

from django.shortcuts import render_to_response, HttpResponseRedirect, HttpResponse, get_object_or_404
from django.template import RequestContext
from assets.models import Project, Host
from assets.models import project_swan, swan_pro, swan_port, gitCode
from django import forms
import ast
from django.contrib.auth.decorators import login_required


# class swan_form(forms.ModelForm):
#     """
#     """
#
#     choose = forms.ChoiceField(widget=forms.RadioSelect, choices=swan_pro, required=True, initial=0, label=u"发布类型")
#     node = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple, choices=[], label=u"主机列表")
#
#     def __init__(self, *args, **kwargs):
#         self.business = kwargs.pop('business', None)
#         super(swan_form, self).__init__(*args, **kwargs)
#         self.fields['ip'].choices = Host.objects.values_list("uuid", "eth1").filter(business=self.business)
#         # self.fields['ip'].choices = Host.objects.values_list("id", "eth1")
#
#     class Meta:
#         model = project_swan
#         fields = [
#             "swan_name",
#             "script",
#             "tgt",
#             "node",
#         ]


# class ProjectForm(forms.ModelForm):
#     node = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple, choices=[], label=u"主机列表")
#
#     def __init__(self, *args, **kwargs):
#         self.business = kwargs.pop('business', None)
#         super(ProjectForm, self).__init__(*args, **kwargs)
#         self.fields['node'].choices = Host.objects.values_list("uuid", "eth1").filter(business=self.business)
#
#     class Meta:
#         model = project_swan
#         fields = [
#             "swan_name",
#             "script",
#             "tgt",
#             'node'
#         ]


# class swan_all_form(forms.ModelForm):
#     """
#     sadf
#     """
#     check_port_status = forms.ChoiceField(widget=forms.RadioSelect(), choices=swan_port, required=True, initial=0,
#                                           label=u"是否检测端口")
#     choose = forms.ChoiceField(widget=forms.RadioSelect(), choices=swan_pro, required=True, initial=1, label=u"发布类型")
#     bat_push = forms.ChoiceField(widget=forms.RadioSelect(), choices=swan_port, required=True, initial=0, label=u"批量发布")
#
#     node = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple, choices=[], label=u"主机列表")
#
#     def __init__(self, *args, **kwargs):
#         self.business = kwargs.pop('business', None)
#         super(swan_all_form, self).__init__(*args, **kwargs)
#         self.fields['ip'].choices = Host.objects.values_list("uuid", "eth1").filter(business=self.business)
#
#     class Meta:
#         model = project_swan
#         fields = [
#             "choose",
#             "swan_name",
#             "config_name",
#             "salt_sls",
#             "bat_push",
#             "check_port_status",
#             "check_port",
#             "node",
#         ]


class GitCodeForm(forms.ModelForm):
    node = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple, choices=[], label=u"主机列表")

    def __init__(self, *args, **kwargs):
        self.business = kwargs.pop('business', None)
        super(GitCodeForm, self).__init__(*args, **kwargs)
        self.fields['node'].choices = Host.objects.values_list("uuid", "eth1").filter(business=self.business)

    class Meta:
        model = project_swan
        fields = [
            "swan_name",
            "code_name",
            "git_code",
            "code_path",
            "git_code_user",
            # "git_tag",
            "tgt",
            "shell",
            "shell_status",
            "CheckUrl",
            'node'
        ]


class GitEditCodeForm(forms.ModelForm):
    node = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple, choices=[], label=u"主机列表")

    def __init__(self, *args, **kwargs):
        self.business = kwargs.pop('business', None)
        super(GitEditCodeForm, self).__init__(*args, **kwargs)
        self.fields['node'].choices = Host.objects.values_list("uuid", "eth1").filter(business=self.business)

    class Meta:
        model = project_swan
        fields = [
            "swan_name",
            "code_name",
            "git_code",
            "code_path",
            "git_code_user",
            "tgt",
            "shell",
            "shell_status",
            "CheckUrl",
            'node'
        ]


class CodeForm(forms.ModelForm):
    class Meta:
        model = gitCode
        fields = [
            "codePath",
            "codeserver",
            "codeFqdn",
        ]


class ShellCodeForm(forms.ModelForm):
    node = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple, choices=[], label=u"主机列表")

    def __init__(self, *args, **kwargs):
        self.business = kwargs.pop('business', None)
        super(ShellCodeForm, self).__init__(*args, **kwargs)
        self.fields['node'].choices = Host.objects.values_list("uuid", "eth1").filter(business=self.business)

    class Meta:
        model = project_swan
        fields = [
            "swan_name",
            "code_name",
            "shell",
            "tgt",
            "CheckUrl",
            'node'
        ]


class JavaCodeForm(forms.ModelForm):
    node = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple, choices=[], label=u"主机列表")

    def __init__(self, *args, **kwargs):
        self.business = kwargs.pop('business', None)
        super(JavaCodeForm, self).__init__(*args, **kwargs)
        self.fields['node'].choices = Host.objects.values_list("uuid", "eth1").filter(business=self.business)

    class Meta:
        model = project_swan
        fields = [
            "swan_name",
            "git_code",
            "code_name",
            "code_path",
            "git_code_user",
            "tgt",
            "tomcat_init",
            "cache",
            "shell",
            "shell_status",
            "CheckUrl",
            'node'
        ]

cmdb/templates/swan/add_code_templates.html
{% extends 'default/base.html' %}
{% load bootstrap %}
{#{% load bootstrap3 %}#}


{% block content %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>code 仓库添加  </h2>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<style>
    .wrapper{margin-top:10px;}
    .wanghui{margin-top:10px;}
    #id_node li{
       list-style-type :none;line-height:25px;
    }
</style>
<div class="wrapper ibox-content">
    <div class="row">
        <div class="ibox float-e-margins">
            <div id="result" >
                <form id="from_data" role="form" action="" method="post">
                    {% csrf_token %}
                    {{ uf |bootstrap }}
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">保存</button>
                        <button class="btn" type="reset">重置</button>
                    </div>
                </form>
             </div>
        </div>
    </div>
</div>


<!-- 右侧菜单栏控制 -->
<script type="text/javascript">


</script>
<script>

 $(function(){
     var three = document.location.pathname.split("/")[5];
        if (str == "default"){
            $("." + str).addClass('active');
        }
        $("." + three).addClass('active');

 });

</script>

{% endblock content %}

cmdb/templates/swan/apply_exec.html
{% extends 'default/base.html' %}
{% load bootstrap %}
{% block content %}
<style>
.voilet-top{margin-top:8px;}
#websocket_rest{margin-top:12px;}
#content-block{margin-top:10px;}
.voilet{margin-left:12px;}
.voilet-left{margin-left:16px;}
.voilet a{margin-left:2px;}
</style>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>自动化发布 | Assets List.</h2>
    </div>
    <div class="col-lg-2">
    </div>
</div>


<div id="content-block">
    <div id="result">
        <form class="form-inline" id="swan_form" >
        {% csrf_token %}
            <div class="row">
                <div class="input-group col-lg-12 voilet-left">
                    <div class="input-group col-lg-3">
                        <select id="project_name" class="form-control select_business" name="project_name">
                            <option value="{{ project_name }}" selected="selected">{{project_name}}</option>
                        </select>
                    </div>
                    <div class="input-group voilet-left voilet-margin">
                        <div id="result_select">
                            <select id="swan_name" class="form-control parameters" name="project_all_tag">
                                <option value="{{ module_name }}" selected="selected">{{ module_name }}</option>
                            </select>
                         </div>
                     </div>
                    <div class="input-group voilet-margin">
                        <div id="result_Parameters">
                            <select id="tgt_name" class="form-control" name="tgt">
                                {% ifequal module_type 0 %}
                                    <option value="" selected="selected">{{ module_tgt }}</option>
                                {% else %}
                                    <option value="" selected="selected">选择项目参数</option>
                                {% endifequal %}
                            </select>
                         </div>
                     </div>
                    <div class="input-group voilet-left voilet-margin">
                        <select id="id-arg" class="form-control" name="arg">
                            <option value="" selected="selected">请选择发布参数</option>
                            <option value="all">all</option>
                            <option value="dynamic">dynamic</option>
                            <option value="static">static</option>
                        </select>
                     </div>
                    <div class="input-group voilet">
                        <span class="input-group-btn">
                           <a class="btn btn-primary swan_push monitor" href="/swan/release/" onclick="return false">发布</a>
                        </span>
                    </div>
                </div>
            </div>

            <div class="row voilet-top">
              <div class="col-lg-6">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="请输入回退版本号">
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="button" >回退</button>
                  </span>
                </div><!-- /input-group -->
              </div><!-- /.col-lg-6 -->
              <div class="col-lg-6">
            </div><!-- /.row -->
          </div>
        <div id="host_rest"></div>
      </form>
        <div class="clearfix visible-xs-block"></div>
      <div id="websocket_rest">
          <table class="table table-striped table-bordered table-hover " id="editable" >
            <thead>
                <tr>
                    <th class="text-center"><input id="select_all" type="checkbox" class="i-checks" name="checkall" value="checkall"></th>
                    <th class="text-center"> eth1 </th>
                    <th class="text-center"> 机柜 </th>
                    <th class="text-center"> 系统状态 </th>
                </tr>
            </thead>
            <tbody>
            {% for post in posts %}
                <tr class="gradeX">
                    <td class="text-center"><input name="node_name" value="{{ post.eth1 }}" type="checkbox"></td>
                    <td class="text-center"> {{ post.eth1 }} </td>
                    <td class="text-center"> {{ post.room_number }} </td>
                    <td class="text-center">
                        <div class="btn-group" data-toggle="buttons">
                            <label class="btn btn-xs btn-success disabled"><input type="radio" name="options" id="option3">
                                {% ifequal post.auto_insatll 0 %}
                                    未安装系统
                                {% endifequal %}
                                {% ifequal post.status 1 %}
                                    OK
                                {% endifequal %}
                                {% ifequal post.status 2 %}
                                    正在安装
                                {% endifequal %}
                            </label>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
</div>

<script>
   $('.swan_push').unbind('click').bind('click',function(){
       var project_name=$("#project_name").val();
       var project_name_all=$("#swan_name").val();
       var project_name_tgt=$("#tgt_name").val();
       if(project_name == ""){
           $("#websocket_rest").html("<div class=\"alert alert-dismissable alert-danger\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">×</button><strong>Warning! </strong>项目名必选</div>");
            return false;
       }
       if(project_name_all == ""){
           $("#websocket_rest").html("<div class=\"alert alert-dismissable alert-warning\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">×</button><strong>Warning! </strong>发布功能必选</div>");
            return false;
       }
       // if(project_name_tgt == ""){
       //     $("#websocket_rest").html("<div class=\"alert alert-dismissable alert-info\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">×</button><strong>Warning! </strong>项目参数必选</div>");
       //      return false;
       // }

       else {
           $.ajax({
           type: "POST",
           url: $(this).attr("href"),                  // 提交的页面
           data: $('#swan_form').serialize(), // 从表单中获取数据
           dataType:'text',
           success: function(data){
               // alert(data);
               $("#voilet_websocket").remove();
                 BootstrapDialog.show({
                     title: "发布日志",
                     message: $('<div></div>').load('/swan/websocket/'),
                     closable: true,
                     closeByBackdrop: false,
                     closeByKeyboard: false
                 });

                //$("#websocket_rest").html(data);
           }
        });
       }
   });

    $(document).on("click","#select_all",function(e){
       var selected = $("#select_all").prop("checked");
       if(selected){
         $("input[name='node_name']").prop('checked',true);
       }else{
         $("input[name='node_name']").prop("checked",false);
       }
     });

</script>

{% endblock content %}

cmdb/templates/swan/apply_tgt.html
{% ifnotequal rst true %}
    <div class="form-group">
        <label for="module_name"  class="col-lg-2 control-label"> 项目参数 <span class="red-fonts">*</span> </label>
        <div id="result_Parameters" class="col-sm-8">
            <select id="tgt_name" name="tgt_name" class="form-control m-b">
                <option value="" selected="selected">选择项目参数</option>
                {% for i in rst_data %}
                    <option value="{{ i.uuid }}">{{ i }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
{% endifnotequal %}

cmdb/templates/swan/edit_swan_git.html
{#{% extends 'user/base.html' %}#}
{% load bootstrap %}
{#{% load bootstrap3 %}#}


{% block content %}
<style>
#id_node li{
   list-style-type :none;line-height:25px;
}
</style>
<div class="wrapper">
    <div class="row">
        <div class="ibox float-e-margins">
            <div id="result">
                <h3>{{ item }} 项目添加发布功能</h3>
                <form id="from_data" role="form" action="/conf/project/edit/{{ item.uuid }}/{{ swan_data.uuid }}/" method="post">
                    {% csrf_token %}
                        {{ uf|bootstrap }}
                        </table>
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">保存</button>
                        <button class="btn" type="reset">重置</button>
                    </div>
                </form>
             </div>
        </div>
    </div>
</div>

<script>
    $(document).on("click","#select_all",function(e){
       var selected = $("#select_all").prop("checked");
       if(selected){
         $("input[name='node']").prop('checked',true);
       }else{
         $("input[name='node']").prop("checked",false);
       }
     });
</script>



{% endblock content %}

cmdb/templates/swan/push_error.html
<div class="alert alert-dismissable alert-danger">
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4>
        Alert!
    </h4> <strong>Warning!</strong>发布接口请求超时，请联系管理员
</div>

<script>
    $(document).ready(function(){
        $(".alert").delay(5000).hide(1000);
    });
</script>

cmdb/templates/swan/select.html
<select id="swan_name" class="form-control" name="project_all_tag">
    <option value="" selected="selected">选择发布分支或参数</option>
    {% for k,v in data.items %}
        <option value="{{ k }}">{{ v }}</option>
    {% endfor %}
</select>

cmdb/templates/swan/select_tgt.html
<select id="tgt_name" class="form-control" name="tgt">
    <option value="" selected="selected">选择项目参数</option>
    {% for i in rst_data %}
        <option value="{{ i }}">{{ i }}</option>
    {% endfor %}
</select>

<script>
    $('#tgt_name').change(function() {
       $("#update_log").show();
        return false;
   });
</script>

cmdb/templates/swan/swan_log.html
{% extends 'default/base.html' %}
{% load bootstrap %}
{#{% load bootstrap3 %}#}


{% block content %}
{#<div class="row wrapper border-bottom white-bg page-heading">#}
{#    <div class="col-lg-10">#}
{#        <h2>发布日志  </h2>#}
{#    </div>#}
{#    <div class="col-lg-2">#}
{#    </div>#}
{#</div>#}
<style>
    .wrapper{margin-top:10px;}
    .wanghui{margin-top:10px;}
    #id_node li{
       list-style-type :none;line-height:25px;
    }
</style>
{#<div class="wrapper ibox-content">#}
{#    <div class="row">#}
{#        <div class="ibox float-e-margins">#}
{#            <div class="col-lg-12">#}
{#                <div class="ibox float-e-margins">#}
{#                    <div class="ibox-title">#}
{#                        <span class="label label-info pull-right">swan</span>#}
{#                        <h5>发布日志</h5>#}
{#                    </div>#}
{#                    <div class="ibox-content inspinia-timeline">#}
{#                        {% for i in log_data %}#}
{#                        <div class="timeline-item">#}
{#                            <div class="row">#}
{#                                <div class="col-xs-3 date">#}
{#                                    <i class="fa fa-pied-piper-alt"></i>#}
{#                                    <small class="text-navy">{{ i.swan_datetime }}</small>#}
{#                                </div>#}
{#                                <div class="col-xs-7 content no-top-border">#}
{#                                    <p class="m-b-xs"><strong><span class="label label-danger">{{ i.username }}</span> </strong></p>#}
{#                                    <p>发布: {{ i.project_name }}</p>#}
{#                                    <p>{{ i.swan_name }} -> {{ i.module_name }}分支</p>#}
{#                                    <p>状态: {{ i.message }}</p>#}
{#                                    {% if i.update_log %}#}
{#                                    <p>更新内容: {{ i.update_log|linebreaksbr }}</p>#}
{#                                    {% endif %}#}
{#                                    <p>{{ i.swan_datetime }}</p>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                        {% endfor %}#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
<div class="wrapper wrapper-content">
            <div class="row animated fadeInRight">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="text-center float-e-margins p-md">
                    <a href="#" class="btn btn-xs btn-primary" id="leftVersion">发布日志排版方式</a>
                    </div>
                    <div class="ibox-content" id="ibox-content">

                        <div id="vertical-timeline" class="vertical-container dark-timeline center-orientation">
                            {% for i in log_data %}
                            <div class="vertical-timeline-block">
                                <div class="vertical-timeline-icon navy-bg">
                                    <i class="fa fa-user-md"></i>
                                </div>

                                <div class="vertical-timeline-content">
                                    <h2>{{ i.username }}</h2>
                                    <p>发布: {{ i.project_name }}</p>
                                    <p>{{ i.swan_name }} -> {{ i.module_name }}分支</p>
                                    <p>状态: {{ i.message }}</p>
                                    {% if i.update_log %}
                                    <p>更新内容: {{ i.update_log|linebreaksbr }}</p>
                                    {% endif %}
                                    <span class="vertical-date">
{#                                        Today <br/>#}
                                        <small>{{ i.swan_datetime }}</small>
                                    </span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
            </div>
        </div>
    <script>
        $(document).ready(function(){
            $('#leftVersion').click(function(event) {
                event.preventDefault();
                $('#vertical-timeline').toggleClass('center-orientation');
            });


        });
    </script>

<!-- 右侧菜单栏控制 -->
{% endblock content %}